FROM node:18-alpine
WORKDIR /app

RUN apk add --no-cache git && \
    git clone https://github.com/alialsuleman/chatService.git .

COPY config/node/.env .env
RUN npm install

EXPOSE 3000
CMD ["node", "server.js"]